# Generated by Django 3.1.2 on 2020-11-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityRouters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
